AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  VpcId:
    Type: String
    Description: ID of the VPC where the resources will be created
  PublicSubnet1:
    Type: String
    Description: ID of the first public subnet in the VPC
  PublicSubnet2:
    Type: String
    Description: ID of the second public subnet in the VPC
Globals:
  Function:
    Environment:
      Variables:
        S3_BUCKET: !Ref S3Bucket
        S3_KEY: txns.csv
        DYNAMO_DB_TABLE: !Ref TransactionSummaryTable


Resources:
  TransactionSummaryEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: src/
      Events:
        ProcessEmail:
          Type: Api
          Properties:
            Path: /process-email
            Method: post
      Policies:
        - SESCrudPolicy:
            IdentityName: '*'
        - SESBulkTemplatedCrudPolicy:
            IdentityName: '*'
        - SESEmailTemplateCrudPolicy: {}
        - S3ReadPolicy:
            BucketName: !Sub "txn-summary-bucket-${AWS::AccountId}"
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionSummaryTable

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "txn-summary-bucket-${AWS::AccountId}"

  TransactionSummaryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TransactionSummary
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  GetTxnAPI:
    Description: "API Gateway endpoint URL for Prod environment to get all transactions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/transactions"
  SendEmailAPI:
    Description: "API Gateway endpoint URL for Prod environment to send an email with transaction summary"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/process-email"
  S3BucketName:
    Description: "S3 bucket to upload the txns.csv file"
    Value: !Ref 'S3Bucket'
